version: '3'
services:
  db:
    image: mongo:4.2.8
    container_name: db
    ports:
      - "4000:27017"
    restart: "always"
  video-streaming:
    image: video-streaming
    build:
      context: ./video-streaming
      dockerfile: Dockerfile-dev
    container_name: video-streaming
    volumes:
      - /tmp/video-streaming/npm-cache:/root/.npm:z
      - ./video-streaming/src:/usr/src/app/src:z
    ports:
      - "4001:80"
    environment:
      - PORT=80
      - NODE_ENV=development
      - VIDEO_STORAGE_HOST=azure-storage
      - VIDEO_STORAGE_PORT=80
      - DB_HOST=mongodb://db:27017
      - DB_NAME=video-streaming
    restart: "no"
  azure-storage:
    image: azure-storage
    build:
      context: ./azure-storage
      dockerfile: Dockerfile-dev
    container_name: azure-storage
    volumes:
      - /tmp/azure-storage/npm-cache:/root/.npm:z
      - ./azure-storage/src:/usr/src/app/src:z
    ports:
      - "4002:80"
    environment:
      - PORT=80
      - NODE_ENV=development
      - STORAGE_ACCOUNT_NAME=flixtubestorage1
      - STORAGE_ACCESS_KEY=hCVnXel5h3Ag2Le89IEM/VZ5J76jJLq9Yb3UMzd0MrOP+DaQDi9d51AwLOf2pYtXw+5BaH4ZkEuF+ASts6IOLw==
    restart: "no"
  history:
    image: history
    build:
      context: ./history
      dockerfile: Dockerfile-dev
    container_name: history
    volumes:
      - /tmp/history/npm-cache:/root/.npm:z
      - ./history/src:/usr/src/app/src:z
    ports:
     - "4003:80"
    environment:
      - PORT=80
      - NODE_ENV=development
    restart: "no"